services:
  api:
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}

    build:
      dockerfile: Dockerfile
      context: ./api.micahnorwoodjordan.com
      args:
        DATABASE_CONNECTION_STRING: ${DATABASE_CONNECTION_STRING}
        DATABASE_USER: ${DATABASE_USER}
        DATABASE_PASSWORD: ${DATABASE_PASSWORD}
        SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
        SERVER_PORT: ${SERVER_PORT}
        SMTP_USERNAME: ${SMTP_USERNAME}
        SMTP_PASSWORD: ${SMTP_PASSWORD}

      
    volumes:
      - ./api.micahnorwoodjordan.com:/srv/api.micahnorwoodjordan.com
      
    environment:
      DATABASE_CONNECTION_STRING: ${DATABASE_CONNECTION_STRING}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SERVER_PORT: ${SERVER_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
