services:
  api:
    ports:
      - 8080:8080
    build:
      dockerfile: api.micahnorwoodjordan.com/Dockerfile
      
    volumes:
      - ./api.micahnorwoodjordan.com:/srv/api.micahnorwoodjordan.com
    # command: bash -c "java -jar ./target/api.micahnorwoodjordan.com-build.jar"
    environment:
      DATABASE_CONNECTION_STRING: ${DATABASE_CONNECTION_STRING}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
