spring:
  application:
    name: api.micahnorwoodjordan.com
  cache:
    type: redis
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: false

  flyway:
    enabled: true
    locations: classpath:db/migrations/mysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: smtp.mailgun.org
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  output:
    ansi:
      enabled: always


logging:
  level:
    org.flywaydb: WARN
    org.hibernate.SQL: WARN
    api.micahnorwoodjordan.com: DEBUG
  pattern:
    console: "%clr([%-5level]){yellow} %clr(%d{yyyy-MM-dd HH:mm:ss}) %clr([%thread]){faint} %clr(%logger{36}){cyan} - %clr([%msg]%n){magenta}"
    file: "%clr([%-5level]){yellow} %clr(%d{yyyy-MM-dd HH:mm:ss}) %clr([%thread]){faint} %clr(%logger{36}){cyan} - %clr([%msg]%n){magenta}"
  file:
    name: /var/log/api.micahnorwoodjordan.com/output.log
