spring:
  server:
    port: ${SERVER_PORT}

  datasource:
    url: ${DATABASE_CONNECTION_STRING}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}

  flyway:
    url: ${DATABASE_CONNECTION_STRING}
    user: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    baseline-on-migrate: true

  mail:
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
